### PR TITLE
chores(makefile): add ut coverage for make test

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @cd1989 @zhujian7 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhujian7** [comment]
```
test:
	go test -v -cover $$(go list ./... | grep -v /vendor | grep -v /test) -coverprofile=coverage.out; \
	go tool cover -func coverage.out | tail -n 1 | awk '{ print "Total coverage: " $$3 }';
```

**Comment by supereagle** [comment]
Still need polish

/hold

**Comment by supereagle** [comment]
@cd1989  Have finished the polish, PTAL

**Pull request merged**
