### PR TITLE
chore(integrationCenter):modify integration data source type key 

### PR DESCRIPTION
**Pull request by huxiangtao**
**What this PR does / why we need it**:

replace integration data source type key to Camel-Case format

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @caosm @cd1989 @qiuxiaolian 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by caosm** [comment]
`chore` or `fix` would be more apropos than `feat`

**Comment by cd1989** [comment]
> `chore` or `fix` would be more apropos than `feat`

Please also change the commit message @huxiangtao

**Pull request merged**
