### PR TITLE
[WIP] Add support for Gitea.

### PR DESCRIPTION
**Pull request by tosone**
**What this PR does / why we need it**:

Add support for Gitea CI/CD.

/cc @zhujian7

**Release note**:

```release-note
Add support for Gitea CI/CD
```

### CODE REVIEW

**Comment by zhujian7** [comment]
@tosone Please declare the supported version scope of Gita in [user-guide](https://github.com/caicloud/cyclone/blob/master/docs/user_guide.md#integration-center)

**Comment by supereagle** [comment]
@tosone Any updates?

**Comment by supereagle** [comment]
@tosone I will close this PR, feel free to reopen it if necessary.

**Pull request closed without merging**
