### PR TITLE
refactor(svn): use alpine base image for svn

### PR DESCRIPTION
**Pull request by zhujian7**
**What this PR does / why we need it**:

Unify base image to `alpine:3.8` (Fix https://github.com/caicloud/cyclone/pull/1364#pullrequestreview-343867201) , and locale setting is no longer needed in the alpine, related PR: https://github.com/caicloud/cyclone/pull/1341.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @supereagle @hyy0322 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
Still WIP?

**Comment by zhujian7** [comment]
> Still WIP?

need more test

**Comment by zhujian7** [comment]
> > Still WIP?
> 
> need more tests

@supereagle @PTAL

**Pull request merged**
