### PR TITLE
feat(wft): refact cron trigger for workflow trigger

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
WIP, need more test.

/hold

**Comment by zhujian7** [comment]
LGTM

**Comment by supereagle** [comment]
Have finished test, all is ok.

/hold cancel

**Pull request merged**
