### PR TITLE
Add Chinese functions introduction

### PR DESCRIPTION
**Pull request by superxi911**

### CODE REVIEW

**Comment by superxi911** [comment]
@gaocegege @zoumo @xiaomuqiao PTAL
I will add English introduction next step.

**Comment by zoumo** [comment]
LGTM

**Comment by xiaomuqiao** [comment]
I feel thet the picture is not very clear.

**Comment by superxi911** [comment]
The originals are clearer. Them may be processed by GitHub.

**Comment by xiaomuqiao** [comment]
LGTM

**Pull request merged**
