### PR TITLE
chore: update swagger api

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @zhujian7 @cd1989 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cd1989** [comment]
There may be new APIs added, so I suggest to update swagger when other parts are ready for the release. 

/hold

**Comment by supereagle** [comment]
Have rebased and updated swagger, @cd1989  PTAL

/hold cancel

**Pull request merged**
