### PR TITLE
chore(*): add OWNERS to help caicloud-bot to manage this repo

### PR DESCRIPTION
**Pull request by supereagle**
**Changes**

  - [x] add CODEOWNERS

### CODE REVIEW

**Comment by bbbmj** [comment]
https://github.com/caicloud/engineering/pull/2586

**Comment by supereagle** [comment]
In order to use `caicloud-bot`, rename `CODEOWNERS` to `OWNERS`

**Comment by supereagle** [comment]
@bbbmj  PTAL

**Pull request merged**
