### PR TITLE
feat: add apis to list dockerfiles from scm

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Add api to list Dockerfiles from SCM repos.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @zhujian7  @cd1989 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhujian7** [comment]
Does bitbucket need this change?

**Comment by supereagle** [comment]
> Does bitbucket need this change?

Yes, I will add.

**Comment by supereagle** [comment]
@zhujian7  This feature for BitBucket has been supported. PTAL

**Pull request merged**
