### PR TITLE
remove docker network

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
PTAL @superxi911 @xiaomuqiao

**Comment by gaocegege** [comment]
It seems that cyclone meets an error.

**Comment by superxi911** [comment]
We maybe need to lengthen the [time](https://github.com/caicloud/cyclone/blob/master/websocket/websocket_test.go#L42) for waiting websocket server start up.  How about 5ms？

**Comment by gaocegege** [comment]
OK but I'm wondering why cyclone is failed.

**Comment by gaocegege** [comment]
PTAL

**Comment by superxi911** [comment]
LGTM

**Pull request merged**
