### PR TITLE
refactor: use alpine base image for watcher

### PR DESCRIPTION
**Pull request by zhujian7**
**What this PR does / why we need it**:

Unify base image to alpine:3.8, Fix #1364 (review)

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @supereagle @hyy0322 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
Still WIP?

**Comment by zhujian7** [comment]
> Still WIP?

work normally.
image

@supereagle ptal

**Pull request merged**
