### PR TITLE
fest: skip ssl verify for gitlab

### PR DESCRIPTION
**Pull request by kz33**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes # 

Reference to # https://github.com/caicloud/service/issues/761

**Special notes for your reviewer**:

/cc @zhujian7 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhujian7** [comment]
@supereagle  should I cherrypick it to the master branch?

**Comment by supereagle** [comment]
> @supereagle should I cherrypick it to the master branch?

SGTM

**Pull request merged**
