### PR TITLE
fix: can not exec worker by docker-type cloud

### PR DESCRIPTION
**Pull request by zhujian7**
**What this PR does / why we need it**:

When running cyclone with docker cloud, the error 
`fail to update event 5c0e4a177014bcadc498fef8 as err: The dotted field 'requests.memory' in 'workerInfo.quota.requests.memory' is not valid for storage.` 
occurred while creating cyclone worker,  and I think we don't need to store quota info in the `Event` 
 Object, so remove it.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @supereagle @cd1989 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
> and I think we don't need to store quota info in the `Event`
> Object, so remove it.

Does this work for k8s cloud?

**Comment by zhujian7** [comment]
@supereagle 
> Does this work for k8s cloud?

Yes, of course.

**Pull request merged**
