### PR TITLE
fix error for the defaut values of some environment variables

### PR DESCRIPTION
**Pull request by supereagle**

### CODE REVIEW

**Comment by gaocegege** [comment]
Hi, Thanks for your contribution first, But I think maybe you should set these env vars in [Dockerfile](https://github.com/caicloud/cyclone/blob/master/Dockerfile).

:)

**Comment by superxi911** [comment]
I agree with @gaocegege . It's unnecessary. Thank you😊

**Comment by supereagle** [comment]
I found this error when run the tests in package `notify/provider`. Run tests after skipped the test case `TestReadConfig`, there will be panic error. The root cause is that these env variables will not be set when skip `TestReadConfig`, then it will use their default values, which are not correct.

At the same time, I think these test cases should be independent and isolated, have no effects on each other.

**Comment by xiaomuqiao** [comment]
yes, your proposal is great. so could you modify these test cases  in package notify/provider?

**Comment by supereagle** [comment]
@xiaomuqiao  Yes. I will commit these changes in another PR.

**Comment by gaocegege** [comment]
@supereagle Cool! 👏

**Comment by supereagle** [comment]
If isolate these test cases, this PR is needed, as these default values are needed in these test cases.  @gaocegege  Could you merge this PR?

**Comment by gaocegege** [comment]
you could

**Comment by gaocegege** [comment]
@xiaomuqiao @supereagle @superxi911 WDYT?

**Comment by superxi911** [comment]
I agree with @gaocegege .

**Comment by supereagle** [comment]
I also agree.  According to the [code](https://github.com/caicloud/cyclone/blob/master/Dockerfile#L15) in Dockerfile, these default values are `CORRECT` values in the image. I think we can closed this PR.

**Comment by gaocegege** [comment]
Yeah thank you for your advice. would you help us to fix these test cases? We'd appreciate it :)

**Comment by supereagle** [comment]
To isolate these test cases, I will unset these envs at the end of `TestReadConfig`, and set wrong envs at the head of `TestSendEmailWithWrongConfig`. 

@gaocegege  @superxi911  @xiaomuqiao   WDYT?

**Comment by gaocegege** [comment]
Great, test cases are all written on my own, and I was rush into increasing the coverage at that time. If you find more bugs in unit test or end-to-end test cases, feel free to fix them :)

**Pull request closed without merging**
