### PR TITLE
Fix typos for apis

### PR DESCRIPTION
**Pull request by supereagle**
## Fixes [ISSUE-XXX](issue-link-address)

**Changes**
   
  - [x] fix typos for JSON name
  - [x] ~Replace `[]*` with `[]`~

**Reviewers**

  - [ ] @superxi911 please review

### CODE REVIEW

**Comment by supereagle** [comment]
@superxi911 Please take a look, and help to merge this PR.

**Comment by ddysher** [comment]
Please create two PRs or two commits, one for typos and one for pointer change. Also add explanation for this change.
>  - [x] Replace `[]*` with `[]`

**Comment by supereagle** [comment]
@ddysher  Have remove the change for `Replace []* with []`, will create another PR for this.

**Comment by ddysher** [comment]
LGTM

**Pull request merged**
