### PR TITLE
refact: scm list api enhancement

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Enhance scm list API, depends on caicloud/nirvana#276.

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @zhujian7 @cd1989 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
Need to update vendor after caicloud/nirvana#276 merged.

/hold

**Comment by supereagle** [comment]
caicloud/nirvana#276 is merged, and have updated vendor.

/hold cancel

**Comment by supereagle** [comment]
@zhujian7  @cd1989  PTAL

/hold cancel

**Comment by zhujian7** [comment]
Is there a better URL path name than `scmrepos`?
I think it is a little weird, how about using `repos` directly?
@supereagle @cd1989  WDYT?

**Comment by supereagle** [comment]
Maybe we will provide api to list repos for registry later.

**Pull request merged**
